//
//  GoodsWorker.swift
//  GoodsUpdater
//
//  Created by Александр on 14.01.2020.
//  Copyright (c) 2020 Utkonos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class GoodsWorker {

    func fetchData(completion: @escaping (Result<[Item], AppError>) -> Void) {
        guard let path = Bundle.main.path(forResource: "goods", ofType: "json") else {
            completion(.failure(AppError(message: "Файл не найден")))
            return
        }
        
        do {
            let data = try Data(contentsOf: URL(fileURLWithPath: path), options: .mappedIfSafe)
            let decoder = JSONDecoder()
            let items = try decoder.decode([Item].self, from: data)
            completion(.success(items))
        } catch {
            completion(.failure(AppError(message: error.localizedDescription)))
        }
    }

}
