//
//  GoodsRouter.swift
//  GoodsUpdater
//
//  Created by Александр on 14.01.2020.
//  Copyright (c) 2020 Utkonos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GoodsRoutingLogic {
    func routeToSomewhere(items: [Goods.DisplayedItem])
}

protocol GoodsDataPassing: class {
    var dataStore: GoodsDataStore? { get }
}

class GoodsRouter: GoodsDataPassing {
    weak var viewController: GoodsViewController?
    var dataStore: GoodsDataStore?
}

// MARK: - GoodsRoutingLogic
extension GoodsRouter: GoodsRoutingLogic {
    
    func routeToSomewhere(items: [Goods.DisplayedItem]) {
        SyncManager.shared.addToChanged(changed: items)
        let vc = GoodsBuilder.build(sort: Goods.SortType.popular)
        SyncManager.shared.add(subscriber: vc)
        viewController?.show(vc, sender: nil)
    }
    
}
